$id: observedSchema
type: object
properties:
  version:
    type: string
  type:
    type: string
  assets:
    type: array
    items:
      type: object
      properties:
        type:
          type: string
        buildType:
          type: string
        src:
          type: string
      required:
        - type
        - src
  module:
    type: string
  selector:
    type: string

required:
  - version
  - type
  - assets
  - module
  - selector
